import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    scrollView: {
      flex: 1,
      backgroundColor: '#f8f8f8',
    },
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'flex-start',
      padding: 20,
      direction: 'rtl',
    },
    profileImageContainer: {
      width: 100,
      height: 100,
      borderRadius: 50,
      marginBottom: 15,
      borderWidth: 2,
      borderColor: '#65558F',
      justifyContent: 'center',
      alignItems: 'center',
    },
    profileImage: {
      width: 100,
      height: 100,
      borderRadius: 50,
      justifyContent: 'center',
      alignItems: 'center',
    },
    plusIconContainer: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 2,
      borderColor: '#65558F',
      backgroundColor: '#eee',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 15,
    },
    name: {
      fontSize: 15,
      marginBottom: 8,
      color: '#65558F',
    },
    infoContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    email: {
      fontSize: 15,
      color: '#65558F',
      marginLeft: 8,
    },
    sectionContainer: {
      width: '100%',
      alignItems: 'flex-start',
      marginTop: 20,
      marginBottom: 10,
      paddingHorizontal: 10,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 10,
      color: '#65558F',
    },
    parentCard: {
      backgroundColor: '#fff',
      padding: 12,
      borderRadius: 8,
      marginBottom: 5,
      width: '100%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    childCard: {
      backgroundColor: '#fff',
      padding: 12,
      borderRadius: 8,
      marginBottom: 10,
      width: '100%',
      borderWidth: 1,
      borderColor: '#ddd',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    childCardContent: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    childImagePlaceholder: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#eee',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
      overflow: 'hidden', // כדי שהתמונה תישאר בתוך העיגול
    },
    childImage: {
      width: '100%',
      height: '100%',
    },
    childInfo: {
      flex: 1,
    },
    parentInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 5,
    },
    childInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    parentText: {
      fontSize: 15,
      color: '#65558F',
      marginLeft: 8,
    },
    childText: {
      fontSize: 15,
      color: '#65558F',
      marginLeft: 8,
    },
    icon: {
      marginRight: 8,
      marginLeft: 8,
      color: '#65558F',
    },
    buttonContainer: {
      flexDirection: 'row',
      marginTop: 25,
    },
    updateButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#007bff', // צבע כחול בולט
      paddingVertical: 12, // קצת יותר ריווח אנכי
      paddingHorizontal: 18, // קצת יותר ריווח אופקי
      borderRadius: 8,
      marginHorizontal: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3,
      elevation: 4, // קצת יותר בולט
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#dc3545',
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 8,
      marginHorizontal: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 3,
    },
    buttonText: {
      color: 'white',
      fontSize: 16,
      marginLeft: 8,
    },
  });