import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flexGrow: 1,
      alignItems: 'center',
      padding: 16,
      backgroundColor: '#F8F8F8',
      flexDirection: 'column',
      direction: 'rtl',
    },
    loadingIndicator: {
      marginTop: 20,
    },
    title: {
      fontSize: 32,
      fontWeight: 'bold',
      color: '#65558F',
      marginBottom: 20,
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    form: {
      width: '100%',
    },
    label: {
      alignSelf: 'flex-start',
      fontSize: 16,
      color: '#65558F',
      marginBottom: 8,
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    inputContainer: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      width: '100%',
      height: 45,
      borderWidth: 1,
      borderColor: '#ccc',
      borderRadius: 8,
      backgroundColor: '#fff',
      paddingHorizontal: 10,
      marginBottom: 10,
    },
    icon: {
      marginLeft: 10,
    },
    input: {
      flex: 1,
      textAlign: 'right',
      writingDirection: 'rtl',
      fontSize: 16,
      color: '#333',
    },
    errorText: {
      color: 'red',
      fontSize: 14,
      alignSelf: 'flex-start',
      marginBottom: 10,
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    button: {
      backgroundColor: '#B3E7F2',
      borderWidth: 1,
      borderColor: '#65558F',
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 30,
      marginVertical: 10,
    },
    buttonText: {
      fontSize: 18,
      color: '#65558F',
      fontWeight: 'bold',
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    helpText: {
      fontSize: 15,
      color: '#007bff',
      textDecorationLine: 'underline',
      textAlign: 'center',
      marginTop: 10,
      writingDirection: 'rtl',
    },
    registerContainer: {
      flexDirection: 'row-reverse',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 16,
    },
    registerText: {
      fontSize: 15,
      color: '#007bff',
      textDecorationLine: 'underline',
      textAlign: 'center',
      marginTop: 10,
      writingDirection: 'rtl',
    },
    registerLink: {
      fontSize: 16,
      color: '#007bff',
      textDecorationLine: 'underline',
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    googleButton: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#AAA',
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 20,
      marginTop: 10,
    },
    googleIcon: {
      width: 20,
      height: 20,
      marginRight: 10,
    },
    googleText: {
      fontSize: 16,
      color: '#555',
    },
  
    logoContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
  });
  