import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: '#fff',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 20,
        textAlign: 'center',
    },
    buttonContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: 10,
        marginBottom: 20,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 10,
        fontSize: 16,
    },
    errorContainer: {
        padding: 16,
        backgroundColor: '#ffebee',
        borderRadius: 8,
        marginVertical: 16,
    },
    errorText: {
        color: '#c62828',
        fontSize: 16,
    },
    storyContainer: {
        flex: 1,
        backgroundColor: '#f5f5f5',
        borderRadius: 8,
        padding: 16,
    },
    paragraphContainer: {
        marginBottom: 24,
        backgroundColor: '#fff',
        borderRadius: 8,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    paragraphText: {
        fontSize: 16,
        lineHeight: 24,
        textAlign: 'right',
        marginBottom: 16,
    },
    imageWrapper: {
        position: 'relative',
        width: '100%',
        aspectRatio: 16 / 9,
        marginBottom: 8,
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: 2,
        borderColor: '#e0e0e0',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 4,
        backgroundColor: '#f8f8f8',
        alignSelf: 'center',
    },
    paragraphImage: {
        width: '100%',
        height: '100%',
        borderRadius: 12,
    },
    imageLoadingOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 12,
    },
    imageCaption: {
        fontSize: 13,
        color: '#666',
        fontStyle: 'italic',
        marginTop: 4,
        marginBottom: 8,
        textAlign: 'center',
    },
}); 