import Constants from 'expo-constants';

const extra = Constants.expoConfig?.extra || Constants.manifest?.extra;

export const API_Somee = extra.API_SOMEE;
export const API_Render_Analyzing = extra.API_RENDER_ANALYZING;
export const API_SOMEE_USER = extra.API_SOMEE_USER;
export const API_SOMEE_USER_REGISTER = extra.API_SOMEE_USER_REGISTER;
export const API_SOMEE_USER_LOGIN = extra.API_SOMEE_USER_LOGIN;
export const API_SOMEE_USER_GET_BY_EMAIL = extra.API_SOMEE_USER_GET_BY_EMAIL;
export const API_SOMEE_USER_ADD_CHILD = extra.API_SOMEE_USER_ADD_CHILD;
export const API_SOMEE_USER_GET_USER_ID = extra.API_SOMEE_USER_GET_USER_ID;
export const API_SOMEE_USER_ALL = extra.API_SOMEE_USER_ALL;
export const API_SOMEE_USER_DELETE = extra.API_SOMEE_USER_DELETE;
export const API_SOMEE_USER_UPDATE = extra.API_SOMEE_USER_UPDATE;
export const API_SOMEE_USER_UPDATE_PROFILE_IMAGE = extra.API_SOMEE_USER_UPDATE_PROFILE_IMAGE;
export const API_SOMEE_USER_GET_BY_ID = extra.API_SOMEE_USER_GET_BY_ID;
export const API_SOMEE_STORY_GENERATE = extra.API_SOMEE_STORY_GENERATE;
export const API_SOMEE_STORY_GET_AVAILABLE = extra.API_SOMEE_STORY_GET_AVAILABLE;
export const API_SOMEE_STORY_GET_BY_ID = extra.API_SOMEE_STORY_GET_BY_ID;
export const API_SOMEE_STORY_GET_FOR_CHILD = extra.API_SOMEE_STORY_GET_FOR_CHILD;
export const API_SOMEE_STORY_RATE = extra.API_SOMEE_STORY_RATE;
export const API_SOMEE_STORY_GET_BOOKS_READ = extra.API_SOMEE_STORY_GET_BOOKS_READ;
export const API_SOMEE_READING_SESSION_REPORT = extra.API_SOMEE_READING_SESSION_REPORT;
export const API_SOMEE_READING_SESSION_REPORT_FILTER = extra.API_SOMEE_READING_SESSION_REPORT_FILTER;
export const API_SOMEE_RANDOM_WORDS = extra.API_SOMEE_RANDOM_WORDS;
